include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart

linter:
  rules:
    avoid_print: false
    avoid_dynamic_calls: false
    constant_identifier_names: false
    public_member_api_docs: false
